import SwiftUI

class CoinMoney : ObservableObject {
    
    @Published var coins = [
        Coin(rupiah: "2000", frontImg: "2000-depan", backImg: "2000-belakang", frontExp: "The front side features the National Hero of the Republic of Indonesia, Mohammad Hoesni Thamrin, as the main image. It includes the national emblem of Garuda Pancasila, images of the Indonesian archipelago, the Jeumpa flower, and several typical Indonesian motifs.", backExp: "The back side showcases the Piring Dance paired with the natural beauty of Ngarai Sianok, combined with the elegance of the Jeumpa flower. The design of the Rp2,000 banknote back side is embellished with several typical Indonesian motifs."),
        Coin(rupiah: "5000", frontImg: "5000-depan", backImg: "5000-belakang", frontExp: "The front side features the National Hero of the Republic of Indonesia, Dr. K.H. Idham Chalid, as the main image. It includes the national emblem of Garuda Pancasila, images of the Indonesian archipelago, the Night Blooming Jasmine flower, and several typical Indonesian motifs.", backExp: "The back side showcases the Gambyong Dance paired with the natural beauty of Mount Bromo, combined with the elegance of the Night Blooming Jasmine flower. The design of the Rp5,000 banknote back side is embellished with several typical Indonesian motifs."),
        Coin(rupiah: "10000", frontImg: "10000-depan", backImg: "10000-belakang", frontExp: "The front side features the National Hero of the Republic of Indonesia, Frans Kaisiepo, as the main image. It includes the national emblem of Garuda Pancasila, images of the Indonesian archipelago, the Rough Forest Cempaka flower, and several typical Indonesian motifs, such as the Asmat Papua Motif and the Shield Citak Asmat Motif.", backExp: "The back side showcases the Pakarena Dance paired with the natural beauty of Wakatobi National Park, combined with the elegance of the Rough Forest Cempaka flower. The design of the Rp10,000 banknote back side is embellished with the Ne'Limbongan Toraja Motif and the Pa'Barana Motif."),
        Coin(rupiah: "20000", frontImg: "20000-depan", backImg: "20000-belakang", frontExp: "The front side features the National Hero of the Republic of Indonesia, Dr. G.S.S.J. Ratulangi, as the main image. It includes the national emblem of Garuda Pancasila, images of the Indonesian archipelago, the Black Orchid flower, and several typical Indonesian motifs.", backExp: "The back side showcases the Gong Dance paired with the natural beauty of Derawan, combined with the elegance of the Black Orchid flower. The design of the Rp20,000 banknote back side is embellished with several typical Indonesian motifs."),
        Coin(rupiah: "50000", frontImg: "50000-depan", backImg: "50000-belakang", frontExp: "The front side features the National Hero of the Republic of Indonesia, Ir. H. Djuanda Kartawidjaja, as the main image. It includes the national emblem of Garuda Pancasila, images of the Indonesian archipelago, the Balinese Frangipani flower, and typical Indonesian motifs.", backExp: "The back side showcases the Legong Dance paired with the natural beauty of Komodo National Park, combined with the elegance of the Balinese Frangipani flower. The design of the Rp50,000 banknote back side is embellished with typical Indonesian motifs."),
        Coin(rupiah: "100000", frontImg: "100000-depan", backImg: "100000-belakang", frontExp: "The front side features the Proclamation Figures of Indonesian Independence, Dr. (H.C.) Ir. Soekarno and Dr. (H.C.) Drs Mohammad Hatta, as the main image. It includes the national emblem of Garuda Pancasila, images of the Indonesian archipelago, the Moon Orchid flower, and several typical Indonesian motifs.", backExp: "The back side showcases the Betawi Mask Dance juxtaposed with the natural beauty of Raja Ampat, combined with the elegance of the Moon Orchid flower known as the Puspa Pesona. The design of the Rp100,000 banknote back side is embellished with typical Indonesian motifs."),
        Coin(rupiah: "50", frontImg: "50-depan", backImg: "50-belakang", frontExp: "On the front of the coin there is an image of a kepodang bird. They live in tropical forests that are widespread in Southeast Asia. In Indonesia alone, this bird species can be found in Sumatra, Java, Bali, Kalimantan, Sulawesi, and Nusa Tenggara.", backExp: "On the back of the coin is the Garuda emblem which is the symbol of Indonesia, the writing Bank Indonesia which regulates the circulation of money in Indonesia, and the writing 1999 which marks the first year this money was circulated."),
        Coin(rupiah: "100", frontImg: "100-depan", backImg: "100-belakang", frontExp: "On the front of the coin there is an inscription of 100 rupiah which indicates the value of money, the writing of Bank Indonesia which regulates the circulation of money in Indonesia, and the writing 2016 which marks the year this money was first circulated. ", backExp: "On the back of the coin is an image of a Herman Johannes's face. Herman Johannes was born in Rote, NTT, May 28, 1912. He is an Indonesian scholar, politician, scientist, professor of Universitas Gadjah Mada (UGM), and Indonesian National Hero. Although more widely known as an educator and scientist, Herman Johannes was recorded to have had a career in the military."),
        Coin(rupiah: "200", frontImg: "200-depan", backImg: "200-belakang", frontExp: "On the front of the coin there is an inscription of 200 rupiah which indicates the value of money, the writing of Bank Indonesia which regulates the circulation of money in Indonesia, and the writing 2016 which marks the year this money was first circulated.", backExp: "On the back of the coin is an image of a Dr. Tjiptomangunkusumo's face. Dr. Tjiptomangunkusumo was born in the village of Pecangakan Jepara, on March 4, 1886. Dr. Tjipto was known not only for his ability to think, but also for his honest personality. He even earned a nickname from his teachers, namely Een Begaald Leerling aka a talented student."),
        Coin(rupiah: "500", frontImg: "500-depan", backImg: "500-belakang", frontExp: "On the front of the coin there is an inscription of 500 rupiah which indicates the value of money, the writing of Bank Indonesia which regulates the circulation of money in Indonesia, and the writing 2016 which marks the year this money was first circulated.", backExp: "On the back of the coin is an image of a Tahi Bonar Simatupang's face. Tahi Bonar Simatupang or better known as T.B Simatupang was born on January 28, 1920 in Sidikalang, North Sumatra. T.B Simatupang took his education in North Sumatra before continuing his AMS in Jakarta. After graduating, he enrolled in military education and was accepted at the KMA (Koniklije Militaire Academie) in Bandung."),
        Coin(rupiah: "1000", frontImg: "1000-depan", backImg: "1000-belakang", frontExp: "On the front of the coin there is an inscription of 1000 rupiah which indicates the value of money, the writing of Bank Indonesia which regulates the circulation of money in Indonesia, and the writing 2016 which marks the year this money was first circulated.", backExp: "On the back of the coin is an image of a I Gusti Ketut Puja's face. I Gusti Ketut Puja is the son of I Gusti Nyoman Raka and Jero Ratna Kusuma who was born on May 19, 1908. Born from a noble family, it was not so difficult for him to get an education and earned a Meester in de Rechten degree from the Rechts Hoga School in Jakarta."),
    ]
}


struct Coin : Identifiable {
    var rupiah : String
    var frontImg : String
    var backImg : String
    var frontExp : String
    var backExp : String
    
    var id = UUID()
    var offset = CGSize.zero
    var rotation : Angle = Angle(degrees: 0)
}
